# QB64 to QBJS $include file injector
# By Hevanafa, 09-09-2025

use strict;
use warnings;
use 5.32.1;
use POSIX;

if (!$ARGV[0]) {
	say "Primary file is required!";
	exit
}

my $primary_file = $ARGV[0];  # "GAME.BAS";
my $outfile = "MAIN.BAS";
my $fh;

open ($fh, "<", $primary_file) or die "Couldn't open $primary_file!";
my @lines = map { chomp; $_ } <$fh>;
close $fh;

# Trim only the right end
@lines = map {
	# $_ = s/^\s+|\s+$//gr;
	$_ = s/\s+$//gr;
} @lines;

if (-e "MAIN.BAS") {
	unlink $outfile or die "Cannot delete $outfile!";
}

open ($fh, ">", $outfile);
say $fh "' Auto-generated by preprocess.pl";
say $fh "' at ".(strftime("%Y-%m-%d %H:%M:%S", localtime time));
say $fh "' Do not edit this file!";

foreach my $line (@lines) {
	if ($line !~ /^'\$include/i) {
		say $fh $line;
		next
	}

	# say "Found \$include line: ".$line;

	my $reversed = scalar reverse $line;
	$reversed =~ /'(.*?)'/;
	my $include_file = scalar reverse $1;

	say "\$include-ing ".$include_file."...";

	say $fh "' ".$include_file;

	open (my $include_content, "<", $include_file);
	my @include_lines = map {
		my $line = $_;
		$line =~ /^\$IncludeOnce/i
		? "' ".$line
		: $line
	} <$include_content>;
	close $include_file;
	print $fh (join "", @include_lines)
}

close $fh;

# Assign readonly property
chmod 0444, $outfile or die "Cannot change permissions for $outfile!";

say "Done processing $outfile";
